version: '3.5'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - SE_START_XVFB=false
      - SE_START_VNC=false
    shm_size: '2g'

  minvandforsyning:
    image: ghcr.io/ttopholm/minvandforsyningdk-scraper:latest
    environment:
      - webdriver-remote-url=http://selenium:4444
      - mqtt-host=[mqtt host]
      - username=[forbrugernummer]
      - password=[adgangskode]
      - utility-code=[forsyning]
     depends_on:
      selenium

