services:
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g'
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 2m
      timeout: 10s
      retries: 3

  minvandforsyning:
    image: ghcr.io/ttopholm/minvandforsyningdk-scraper:latest
    restart: always
    environment:
      - webdriver-remote-url=http://selenium:4444
      - mqtt-host=[mqtt host]
      - username=[forbrugernummer]
      - password=[adgangskode]
      - utility-code=[forsyning]
     depends_on:
      selenium:
        condition: service_healthy

